# Minimal Netlify configuration for ThorEye Audit System

[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Path = {exclude = ["/api/*", "/.netlify/functions/*"]}}

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/ws/*"
  to = "/.netlify/functions/websocket/:splat"
  status = 200
  force = true

# Headers
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, PATCH, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Build environment
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefer-offline --no-audit"
