services:
  - type: web
    name: thoreye-audit-system
    env: node
    region: singapore
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
    autoDeploy: true
    rootDir: .
    scaling:
      minInstances: 1
      maxInstances: 3